=== KnowledgeFinder/instance-example/webservice-config/src/main/resources/config/bibtex.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT bibtex (types,tags)>
<!ELEMENT types (type)*>
<!ELEMENT tags (tag)*>
<!ELEMENT type (name,value)>
<!ELEMENT tag (name,value)>
<!ELEMENT name (#PCDATA)> 
<!ELEMENT value (#PCDATA)>

=== KnowledgeFinder/instance-example/webservice-config/target/KnowledgeFinderWebservice/WEB-INF/classes/config/bibtex.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2016 DLR - German Aerospace Center
   
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
   
    http://www.apache.org/licenses/LICENSE-2.0
   
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
 -->

<!DOCTYPE bibtex SYSTEM "bibtex.dtd">

<bibtex>
<types/>
<tags>
	<tag>
		<name>Author</name>
		<value>authors</value>
	</tag>
	<tag>
		<name>Title</name>
		<value>title</value>
	</tag>
	<tag>
		<name>Url</name>
		<value>externalLink</value>
	</tag>
	<tag>
		<name>Keywords</name>
		<value>keywords</value>
	</tag>
	<tag>
		<name>Publisher</name>
		<value>publisher</value>
	</tag>
	<tag>
		<name>Abstract</name>
		<value>description</value>
	</tag>
	<tag>
		<name>Year</name>
		<value>publishDate</value>
	</tag>
</tags>
</bibtex>
